name: margit
favicon: null
layout_spectrum: 0.15250470768660307
typography_spectrum: 0.6095223953016102
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5492508355528116
  lightness: 0.9669137848541141
  saturation: 0.42457024939358234
  rhythmicContrast: 0.09267637738958001
purpose: []
